### ISSUE TITLE
Can't delete search bar contents in firefox

### ISSUE THREAD

**Issue by fabiocolacio** [momentumfrc/Scouting-Website#14]
## The Issue:
- After entering a number, you cannot delete your entry unless you hit the close search bar button.
- Likely related to the *pattern* attribute there, but I don't know much about regex.

## Tested with:
- Firefox for Android
- Firefox for OS X

I haven't been able to reproduce the problem with other browsers.

**Comment by jordan-powers** [comment]
Error is reproducible in firefox on windows. Am investigating now

**Comment by jordan-powers** [comment]
I didn't mean to close it

**Comment by jordan-powers** [comment]
fixed in commit e75004a3373b38fc69e6e44e7b2d38836525e0de
